package io.github.vkb24312.Bloop;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Main {

    public static void main(String[] args) throws InterruptedException {
        JFrame bigFrame = new JFrame("Microphotometadosic pill (Dr. Pill)");
        bigFrame.setSize(300, 300);
        bigFrame.setDefaultCloseOperation(3);
        
        JPanel bigPanel = new JPanel();
        bigFrame.add(bigPanel);
        bigPanel.setLayout(new BorderLayout());
        
        String[] questions = new String[]{
            "Your name",
            
            "Your Age in years",
            "Your Mass in kilos",
            "Your Sex (male/female)",
            "Any diseases you or a family member have had in the past (Separate by comma)",
            "The email of your doctor"
        };
        
        String[] answers = new String[questions.length];
    
        for (int i = 0; i < answers.length; i++) answers[i] = "Answer placeholder";
        
        JPanel helloPanel = new JPanel();
        JLabel hello = new JLabel("Hi. Please answer the questions below");
        helloPanel.add(hello);
        bigPanel.add(helloPanel, BorderLayout.PAGE_START);
        
        JPanel questionPanel = new JPanel();
        JLabel currentQuestion = new JLabel("A question should appear here");
        questionPanel.add(currentQuestion);
        bigPanel.add(questionPanel, BorderLayout.LINE_START);
        
        JPanel answerPanel = new JPanel();
        JTextField currentAnswer = new JTextField(answers[0]);
        answerPanel.add(currentAnswer);
        bigPanel.add(answerPanel, BorderLayout.LINE_END);
        
        JPanel submitPanel = new JPanel();
        JButton back = new JButton("back");
        back.setEnabled(false);
        JButton next = new JButton("next");
        submitPanel.add(back);
        submitPanel.add(next);
        bigPanel.add(submitPanel, BorderLayout.PAGE_END);
        
        bigFrame.setVisible(true);
        bigFrame.pack();
        
        
        
        
        var w = new Object(){
            boolean finished;
            int currentIndex = 0;
        };
        
        back.addActionListener(e -> {
            if(w.currentIndex==1){
                back.setEnabled(false);
            } else if(w.currentIndex == answers.length-1){
                next.setText("next");
            }
            
            if(w.currentIndex>0){
                w.currentIndex--;
            }
            System.out.println(w.currentIndex);
            
            currentQuestion.setText(questions[w.currentIndex]);
    
            answers[w.currentIndex+1] = currentAnswer.getText();
            currentAnswer.setText("");
            if (answers[w.currentIndex] != null) currentAnswer.setText(answers[w.currentIndex]);
            bigFrame.pack();
        });
        
        next.addActionListener(e -> {
            if(w.currentIndex == 0){
                back.setEnabled(true);
            } else if(w.currentIndex == answers.length-2){
                next.setText("finish");
            }
            
            if(w.currentIndex<answers.length-1){
                w.currentIndex++;
            } else {
                w.finished = true;
                System.out.print("");
            }
            System.out.println(w.currentIndex);
            
            currentQuestion.setText(questions[w.currentIndex]);
            
            answers[w.currentIndex-1] = currentAnswer.getText();
            currentAnswer.setText("");
            if (answers[w.currentIndex] != null) currentAnswer.setText(answers[w.currentIndex]);
            bigFrame.pack();
        });
        
        while(!w.finished){
            Thread.sleep(10);
        }
        
        bigFrame.removeAll();
        
        
        bigFrame.add(bigPanel);
        JTextArea email = new JTextArea();
        bigPanel.add(email);
        
        email.setText(
            "(This is an automated email generated by the Microphotometadosic Pill Team (Dr. Pill)\n" +
            "Hello. I am " + answers[0] + "."
        );
    }
}
